// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: stampledgerchain/stampledgerchain/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the stampledgerchain module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// stamps is the list of all stamps
	Stamps []Stamp `protobuf:"bytes,2,rep,name=stamps,proto3" json:"stamps"`
	// documents is the list of all stored documents
	Documents []DocumentStorage `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents"`
	// entities is the list of all entity accounts
	Entities []EntityAccount `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities"`
	// spec_versions is the list of all spec versions
	SpecVersions []SpecVersion `protobuf:"bytes,5,rep,name=spec_versions,json=specVersions,proto3" json:"spec_versions"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a8ccb74ac876602, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetStamps() []Stamp {
	if m != nil {
		return m.Stamps
	}
	return nil
}

func (m *GenesisState) GetDocuments() []DocumentStorage {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *GenesisState) GetEntities() []EntityAccount {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *GenesisState) GetSpecVersions() []SpecVersion {
	if m != nil {
		return m.SpecVersions
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "stampledgerchain.stampledgerchain.v1.GenesisState")
}

func init() {
	proto.RegisterFile("stampledgerchain/stampledgerchain/v1/genesis.proto", fileDescriptor_2a8ccb74ac876602)
}

var fileDescriptor_2a8ccb74ac876602 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd2, 0xb1, 0x4a, 0xc3, 0x40,
	0x18, 0x07, 0xf0, 0xc4, 0xd6, 0x62, 0xaf, 0x75, 0x30, 0x38, 0x84, 0x0e, 0xb1, 0x88, 0x43, 0xa9,
	0x9a, 0x98, 0x16, 0x1f, 0xc0, 0x52, 0x11, 0x27, 0xa5, 0x45, 0x41, 0x11, 0xe4, 0x4c, 0x3f, 0x62,
	0xc0, 0xdc, 0x85, 0x7c, 0xd7, 0x62, 0xdf, 0xc2, 0xc7, 0x70, 0x74, 0xf6, 0x09, 0x3a, 0x76, 0x74,
	0x12, 0x69, 0x07, 0x5f, 0x43, 0x72, 0x39, 0xac, 0x98, 0xe5, 0x96, 0x70, 0xfc, 0xc9, 0xff, 0xc7,
	0x7d, 0xc9, 0x47, 0x3a, 0x28, 0x68, 0x9c, 0x3c, 0xc1, 0x28, 0x84, 0x34, 0x78, 0xa4, 0x11, 0xf3,
	0x0a, 0xc1, 0xc4, 0xf7, 0x42, 0x60, 0x80, 0x11, 0xba, 0x49, 0xca, 0x05, 0xb7, 0xf6, 0xfe, 0xbf,
	0xe2, 0x16, 0x82, 0x89, 0xdf, 0xd8, 0xa2, 0x71, 0xc4, 0xb8, 0x27, 0x9f, 0x79, 0xb1, 0xb1, 0x1d,
	0xf2, 0x90, 0xcb, 0xa3, 0x97, 0x9d, 0x54, 0xea, 0x6b, 0x5d, 0x21, 0xa1, 0x29, 0x8d, 0xd5, 0x0d,
	0x1a, 0x47, 0x5a, 0x15, 0x99, 0xe5, 0x8d, 0xdd, 0xf7, 0x12, 0xa9, 0x9f, 0xe5, 0x53, 0x0c, 0x05,
	0x15, 0x60, 0x5d, 0x90, 0x4a, 0x4e, 0xda, 0x66, 0xd3, 0x6c, 0xd5, 0x3a, 0x07, 0xae, 0xce, 0x54,
	0xee, 0xa5, 0xec, 0xf4, 0xaa, 0xb3, 0xcf, 0x1d, 0xe3, 0xf5, 0xfb, 0xad, 0x6d, 0x0e, 0x14, 0x63,
	0x9d, 0x93, 0x8a, 0x2c, 0xa0, 0xbd, 0xd6, 0x2c, 0xb5, 0x6a, 0x9d, 0x7d, 0x3d, 0x70, 0x98, 0x65,
	0xbd, 0x72, 0xe6, 0x0d, 0x14, 0x60, 0xdd, 0x90, 0xea, 0x88, 0x07, 0xe3, 0x18, 0x98, 0x40, 0xbb,
	0x24, 0xb5, 0x63, 0x3d, 0xad, 0xaf, 0x6a, 0x43, 0xc1, 0x53, 0x1a, 0x82, 0x72, 0x57, 0x9a, 0x75,
	0x45, 0x36, 0x80, 0x89, 0x48, 0x44, 0x80, 0x76, 0x59, 0xca, 0x5d, 0x3d, 0xf9, 0x34, 0x6b, 0x4d,
	0x4f, 0x82, 0x80, 0x8f, 0x99, 0x50, 0xee, 0x2f, 0x65, 0xdd, 0x91, 0x4d, 0x4c, 0x20, 0xb8, 0x9f,
	0x40, 0x8a, 0x11, 0x67, 0x68, 0xaf, 0x4b, 0xdb, 0xd7, 0xfc, 0x06, 0x09, 0x04, 0xd7, 0x79, 0x53,
	0xc9, 0x75, 0x5c, 0x45, 0xd8, 0xeb, 0xcf, 0x16, 0x8e, 0x39, 0x5f, 0x38, 0xe6, 0xd7, 0xc2, 0x31,
	0x5f, 0x96, 0x8e, 0x31, 0x5f, 0x3a, 0xc6, 0xc7, 0xd2, 0x31, 0x6e, 0xdb, 0x7f, 0xb8, 0xc3, 0xfc,
	0xc7, 0x3f, 0x17, 0x77, 0x41, 0x4c, 0x13, 0xc0, 0x87, 0x8a, 0xdc, 0x84, 0xee, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x21, 0x54, 0xd2, 0xa2, 0xf3, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SpecVersions) > 0 {
		for iNdEx := len(m.SpecVersions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SpecVersions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Entities) > 0 {
		for iNdEx := len(m.Entities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Documents) > 0 {
		for iNdEx := len(m.Documents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Documents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Stamps) > 0 {
		for iNdEx := len(m.Stamps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stamps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Stamps) > 0 {
		for _, e := range m.Stamps {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Documents) > 0 {
		for _, e := range m.Documents {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Entities) > 0 {
		for _, e := range m.Entities {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SpecVersions) > 0 {
		for _, e := range m.SpecVersions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stamps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stamps = append(m.Stamps, Stamp{})
			if err := m.Stamps[len(m.Stamps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Documents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Documents = append(m.Documents, DocumentStorage{})
			if err := m.Documents[len(m.Documents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entities = append(m.Entities, EntityAccount{})
			if err := m.Entities[len(m.Entities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecVersions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpecVersions = append(m.SpecVersions, SpecVersion{})
			if err := m.SpecVersions[len(m.SpecVersions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
