export interface Municipality {
  name: string
  county: string
  state: string
  population: number | null
}

export interface PipelineProject {
  title: string
  municipality: string
  county: string
  state: string
  signalScore: number
  status: string
  projectType: string
  budgetLow: number
  budgetHigh: number
}

export const PROJECT_TYPE_LABELS: Record<string, string> = {
  cyber_security: 'Cybersecurity',
  lift_station: 'Lift Station',
  storage_tank: 'Storage Tank',
  scada: 'SCADA',
  collection_system: 'Collection System',
  wwtp_upgrade: 'WWTP Upgrade',
  biosolids: 'Biosolids',
  well_facility: 'Well Facility',
  wtp_upgrade: 'WTP Upgrade',
  water_main: 'Water Main',
}

export const municipalities: Municipality[] = [
  { name: "ABBOTSFORD", county: "MARATHON", state: "WI", population: 2100 },
  { name: "ABRAMS", county: "OCONTO", state: "WI", population: 306 },
  { name: "ALBANY", county: "GREEN", state: "WI", population: 1065 },
  { name: "ALGOMA", county: "WINNEBAGO", state: "WI", population: 3219 },
  { name: "ALLENTON", county: "WASHINGTON", state: "WI", population: 940 },
  { name: "ALMA", county: "BUFFALO", state: "WI", population: 792 },
  { name: "ALMA CENTER, VILLAGE OF", county: "JACKSON", state: "WI", population: null },
  { name: "ALMENA", county: "BARRON", state: "WI", population: 749 },
  { name: "AMERY", county: "POLK", state: "WI", population: 2959 },
  { name: "AMHERST", county: "PORTAGE", state: "WI", population: 1033 },
  { name: "ANTIGO", county: "LANGLADE", state: "WI", population: 8058 },
  { name: "ARCADIA", county: "TREMPEALEAU", state: "WI", population: 3720 },
  { name: "ARGYLE", county: "LAFAYETTE", state: "WI", population: 875 },
  { name: "ARKANSAW", county: "PEPIN", state: "WI", population: 371 },
  { name: "ARLINGTON", county: "COLUMBIA", state: "WI", population: 947 },
  { name: "ASHIPPUN", county: "DODGE", state: "WI", population: 972 },
  { name: "ASHLAND", county: "ASHLAND", state: "WI", population: 7884 },
  { name: "ATHENS", county: "MARATHON", state: "WI", population: 1005 },
  { name: "AUBURNDALE", county: "WOOD", state: "WI", population: 807 },
  { name: "AUGUSTA", county: "EAU CLAIRE", state: "WI", population: 1381 },
  { name: "AVOCA", county: "IOWA", state: "WI", population: 467 },
  { name: "Appleton", county: "Outagamie", state: "WI", population: 74873 },
  { name: "BAILEYS HARBOR", county: "DOOR", state: "WI", population: 280 },
  { name: "BALDWIN VILLAGE", county: "ROCK", state: "WI", population: null },
  { name: "BALSAM LAKE, VILLAGE OF", county: "POLK", state: "WI", population: null },
  { name: "BANGOR", county: "LA CROSSE", state: "WI", population: 1409 },
  { name: "BARABOO", county: "SAUK", state: "WI", population: 12506 },
  { name: "BARNEVELD", county: "IOWA", state: "WI", population: 1485 },
  { name: "BARRON", county: "BARRON", state: "WI", population: 3689 },
  { name: "BAY CITY", county: "PIERCE", state: "WI", population: 358 },
  { name: "BEAR CREEK", county: "OUTAGAMIE", state: "WI", population: 271 },
  { name: "BEAVER DAM", county: "DODGE", state: "WI", population: 16629 },
  { name: "BELGIUM", county: "OZAUKEE", state: "WI", population: 2648 },
  { name: "BELLEVILLE", county: "DANE", state: "WI", population: 2628 },
  { name: "BELMONT", county: "LAFAYETTE", state: "WI", population: 996 },
  { name: "BENTON", county: "LAFAYETTE", state: "WI", population: 904 },
  { name: "BERLIN", county: "GREEN LAKE", state: "WI", population: 5523 },
  { name: "BIRNAMWOOD", county: "SHAWANO", state: "WI", population: 688 },
  { name: "BLACK CREEK", county: "OUTAGAMIE", state: "WI", population: 1263 },
  { name: "BLACK RIVER FALLS", county: "JACKSON", state: "WI", population: 3514 },
  { name: "BLANCHARDVILLE", county: "LAFAYETTE", state: "WI", population: 659 },
  { name: "BLOOMER", county: "CHIPPEWA", state: "WI", population: 3691 },
  { name: "BLOOMFIELD, TOWN OF", county: "WALWORTH", state: "WI", population: null },
  { name: "BLOOMINGTON", county: "GRANT", state: "WI", population: 716 },
  { name: "Beloit", county: "Rock", state: "WI", population: 36554 },
  { name: "Brookfield", county: "Waukesha", state: "WI", population: 41592 },
  { name: "CORNUCOPIA", county: "BAYFIELD", state: "WI", population: 104 },
  { name: "De Pere", county: "Brown", state: "WI", population: 25410 },
  { name: "Eau Claire", county: "Eau Claire", state: "WI", population: 69421 },
  { name: "FARMINGTON TN", county: "LA CROSSE", state: "WI", population: null },
  { name: "FLORENCE", county: "FLORENCE", state: "WI", population: 391 },
  { name: "FRIENDSHIP", county: "ADAMS", state: "WI", population: 737 },
  { name: "Fitchburg", county: "Dane", state: "WI", population: 31566 },
  { name: "Fond du Lac", county: "Fond du Lac", state: "WI", population: 44678 },
  { name: "GURNEY", county: "IRON", state: "WI", population: null },
  { name: "Green Bay", county: "Brown", state: "WI", population: 107395 },
  { name: "Greenfield", county: "Milwaukee", state: "WI", population: 37361 },
  { name: "Janesville", county: "Rock", state: "WI", population: 65813 },
  { name: "Kenosha", county: "Kenosha", state: "WI", population: 99147 },
  { name: "La Crosse", county: "La Crosse", state: "WI", population: 52680 },
  { name: "Madison", county: "Dane", state: "WI", population: 275568 },
  { name: "Manitowoc", county: "Manitowoc", state: "WI", population: 34553 },
  { name: "Marshfield", county: "Wood", state: "WI", population: 18718 },
  { name: "Menasha", county: "Winnebago", state: "WI", population: 18130 },
  { name: "Mequon", county: "Ozaukee", state: "WI", population: 25259 },
  { name: "Middleton", county: "Dane", state: "WI", population: 22235 },
  { name: "Milwaukee", county: "Milwaukee", state: "WI", population: 569756 },
  { name: "Neenah", county: "Winnebago", state: "WI", population: 27409 },
  { name: "ODANAH", county: "ASHLAND", state: "WI", population: 118 },
  { name: "Oshkosh", county: "Winnebago", state: "WI", population: 66247 },
  { name: "Racine", county: "Racine", state: "WI", population: 77155 },
  { name: "SHERRY", county: "WOOD", state: "WI", population: null },
  { name: "Sheboygan", county: "Sheboygan", state: "WI", population: 49812 },
  { name: "Stevens Point", county: "Portage", state: "WI", population: 26717 },
  { name: "Sun Prairie", county: "Dane", state: "WI", population: 35954 },
  { name: "Superior", county: "Douglas", state: "WI", population: 668 },
  { name: "WENTWORTH", county: "DOUGLAS", state: "WI", population: null },
  { name: "WISCONSIN DELLS", county: "JUNEAU", state: "WI", population: 2763 },
  { name: "WOOD COUNTY", county: "WOOD", state: "WI", population: null },
  { name: "Watertown", county: "Jefferson", state: "WI", population: 22873 },
  { name: "Waukesha", county: "Waukesha", state: "WI", population: 8479 },
  { name: "Wausau", county: "Marathon", state: "WI", population: 39893 },
  { name: "West Allis", county: "Milwaukee", state: "WI", population: 60697 },
]

export const pipelineProjects: PipelineProject[] = [
  { title: "West Allis Cybersecurity Compliance Upgrade", municipality: "West Allis", county: "Milwaukee", state: "WI", signalScore: 97, status: "active", projectType: "cyber_security", budgetLow: 1193213, budgetHigh: 1909577 },
  { title: "Greenfield Lift Station Improvements", municipality: "Greenfield", county: "Milwaukee", state: "WI", signalScore: 97, status: "active", projectType: "lift_station", budgetLow: 566558, budgetHigh: 3595944 },
  { title: "Stevens Point Water Storage Tank", municipality: "Stevens Point", county: "Portage", state: "WI", signalScore: 97, status: "active", projectType: "storage_tank", budgetLow: 1768106, budgetHigh: 4152437 },
  { title: "Superior SCADA System Upgrade", municipality: "Superior", county: "Douglas", state: "WI", signalScore: 96, status: "active", projectType: "scada", budgetLow: 904800, budgetHigh: 2171836 },
  { title: "Stevens Point SCADA System Upgrade", municipality: "Stevens Point", county: "Portage", state: "WI", signalScore: 95, status: "active", projectType: "scada", budgetLow: 1015369, budgetHigh: 2901495 },
  { title: "Madison Water Storage Tank", municipality: "Madison", county: "Dane", state: "WI", signalScore: 94, status: "active", projectType: "storage_tank", budgetLow: 1722579, budgetHigh: 6523722 },
  { title: "Sun Prairie SCADA System Upgrade", municipality: "Sun Prairie", county: "Dane", state: "WI", signalScore: 94, status: "active", projectType: "scada", budgetLow: 1052625, budgetHigh: 2345947 },
  { title: "Appleton Water Storage Tank", municipality: "Appleton", county: "Outagamie", state: "WI", signalScore: 94, status: "active", projectType: "storage_tank", budgetLow: 1757198, budgetHigh: 4616758 },
  { title: "Fond du Lac Water Storage Tank", municipality: "Fond du Lac", county: "Fond du Lac", state: "WI", signalScore: 92, status: "active", projectType: "storage_tank", budgetLow: 1417615, budgetHigh: 6757281 },
  { title: "Greenfield Collection System Rehabilitation", municipality: "Greenfield", county: "Milwaukee", state: "WI", signalScore: 91, status: "active", projectType: "collection_system", budgetLow: 2176789, budgetHigh: 11044241 },
  { title: "Marshfield Collection System Rehabilitation", municipality: "Marshfield", county: "Wood", state: "WI", signalScore: 91, status: "active", projectType: "collection_system", budgetLow: 2686005, budgetHigh: 6948346 },
  { title: "Menasha Cybersecurity Compliance Upgrade", municipality: "Menasha", county: "Winnebago", state: "WI", signalScore: 89, status: "active", projectType: "cyber_security", budgetLow: 706839, budgetHigh: 1836209 },
  { title: "Beloit SCADA System Upgrade", municipality: "Beloit", county: "Rock", state: "WI", signalScore: 89, status: "active", projectType: "scada", budgetLow: 801032, budgetHigh: 1586158 },
  { title: "Watertown Lift Station Improvements", municipality: "Watertown", county: "Jefferson", state: "WI", signalScore: 88, status: "active", projectType: "lift_station", budgetLow: 700044, budgetHigh: 2214501 },
  { title: "Racine WWTP Upgrade", municipality: "Racine", county: "Racine", state: "WI", signalScore: 82, status: "active", projectType: "wwtp_upgrade", budgetLow: 5908794, budgetHigh: 22856573 },
  { title: "De Pere WWTP Upgrade", municipality: "De Pere", county: "Brown", state: "WI", signalScore: 82, status: "active", projectType: "wwtp_upgrade", budgetLow: 5888166, budgetHigh: 38445250 },
  { title: "Milwaukee Cybersecurity Compliance Upgrade", municipality: "Milwaukee", county: "Milwaukee", state: "WI", signalScore: 80, status: "active", projectType: "cyber_security", budgetLow: 392765, budgetHigh: 1504071 },
  { title: "Manitowoc Biosolids Handling Improvements", municipality: "Manitowoc", county: "Manitowoc", state: "WI", signalScore: 79, status: "active", projectType: "biosolids", budgetLow: 1667659, budgetHigh: 13798214 },
  { title: "Watertown Cybersecurity Compliance Upgrade", municipality: "Watertown", county: "Jefferson", state: "WI", signalScore: 79, status: "active", projectType: "cyber_security", budgetLow: 534834, budgetHigh: 1923554 },
  { title: "Neenah Water Storage Tank", municipality: "Neenah", county: "Winnebago", state: "WI", signalScore: 77, status: "active", projectType: "storage_tank", budgetLow: 1540104, budgetHigh: 5500817 },
  { title: "Kenosha Collection System Rehabilitation", municipality: "Kenosha", county: "Kenosha", state: "WI", signalScore: 76, status: "active", projectType: "collection_system", budgetLow: 2511226, budgetHigh: 14163368 },
  { title: "Waukesha SCADA System Upgrade", municipality: "Waukesha", county: "Waukesha", state: "WI", signalScore: 74, status: "active", projectType: "scada", budgetLow: 501586, budgetHigh: 1754056 },
  { title: "Racine SCADA System Upgrade", municipality: "Racine", county: "Racine", state: "WI", signalScore: 74, status: "active", projectType: "scada", budgetLow: 1147286, budgetHigh: 2784149 },
  { title: "Greenfield Well Facility Upgrade", municipality: "Greenfield", county: "Milwaukee", state: "WI", signalScore: 74, status: "active", projectType: "well_facility", budgetLow: 2772664, budgetHigh: 4844903 },
  { title: "Marshfield Water Treatment Plant Upgrade", municipality: "Marshfield", county: "Wood", state: "WI", signalScore: 74, status: "active", projectType: "wtp_upgrade", budgetLow: 3893394, budgetHigh: 33792008 },
  { title: "Mequon Water Storage Tank", municipality: "Mequon", county: "Ozaukee", state: "WI", signalScore: 73, status: "active", projectType: "storage_tank", budgetLow: 1963930, budgetHigh: 7417294 },
  { title: "Janesville Well Facility Upgrade", municipality: "Janesville", county: "Rock", state: "WI", signalScore: 72, status: "active", projectType: "well_facility", budgetLow: 2125940, budgetHigh: 6072888 },
  { title: "Brookfield Collection System Rehabilitation", municipality: "Brookfield", county: "Waukesha", state: "WI", signalScore: 72, status: "active", projectType: "collection_system", budgetLow: 2810105, budgetHigh: 10853662 },
  { title: "Janesville Cybersecurity Compliance Upgrade", municipality: "Janesville", county: "Rock", state: "WI", signalScore: 72, status: "active", projectType: "cyber_security", budgetLow: 524096, budgetHigh: 1140510 },
  { title: "Watertown Cybersecurity Compliance Upgrade", municipality: "Watertown", county: "Jefferson", state: "WI", signalScore: 71, status: "active", projectType: "cyber_security", budgetLow: 409893, budgetHigh: 1359773 },
  { title: "Waukesha SCADA System Upgrade", municipality: "Waukesha", county: "Waukesha", state: "WI", signalScore: 69, status: "active", projectType: "scada", budgetLow: 525083, budgetHigh: 2629163 },
  { title: "Fitchburg Cybersecurity Compliance Upgrade", municipality: "Fitchburg", county: "Dane", state: "WI", signalScore: 68, status: "active", projectType: "cyber_security", budgetLow: 997920, budgetHigh: 1764804 },
  { title: "Brookfield Water Treatment Plant Upgrade", municipality: "Brookfield", county: "Waukesha", state: "WI", signalScore: 68, status: "active", projectType: "wtp_upgrade", budgetLow: 3534244, budgetHigh: 18818268 },
  { title: "Marshfield Water Main Replacement", municipality: "Marshfield", county: "Wood", state: "WI", signalScore: 67, status: "active", projectType: "water_main", budgetLow: 1054295, budgetHigh: 5569788 },
  { title: "Neenah Well Facility Upgrade", municipality: "Neenah", county: "Winnebago", state: "WI", signalScore: 65, status: "active", projectType: "well_facility", budgetLow: 2280371, budgetHigh: 5296665 },
  { title: "West Allis Water Storage Tank", municipality: "West Allis", county: "Milwaukee", state: "WI", signalScore: 65, status: "active", projectType: "storage_tank", budgetLow: 1256885, budgetHigh: 4787540 },
  { title: "Racine WWTP Upgrade", municipality: "Racine", county: "Racine", state: "WI", signalScore: 65, status: "active", projectType: "wwtp_upgrade", budgetLow: 5389091, budgetHigh: 41866534 },
  { title: "Watertown Biosolids Handling Improvements", municipality: "Watertown", county: "Jefferson", state: "WI", signalScore: 64, status: "active", projectType: "biosolids", budgetLow: 1945311, budgetHigh: 6840761 },
  { title: "Waukesha Water Treatment Plant Upgrade", municipality: "Waukesha", county: "Waukesha", state: "WI", signalScore: 64, status: "active", projectType: "wtp_upgrade", budgetLow: 3737920, budgetHigh: 36277442 },
  { title: "Manitowoc Water Treatment Plant Upgrade", municipality: "Manitowoc", county: "Manitowoc", state: "WI", signalScore: 63, status: "active", projectType: "wtp_upgrade", budgetLow: 3155688, budgetHigh: 26297613 },
  { title: "Mequon Water Main Replacement", municipality: "Mequon", county: "Ozaukee", state: "WI", signalScore: 63, status: "active", projectType: "water_main", budgetLow: 1614865, budgetHigh: 8116740 },
  { title: "Mequon Water Treatment Plant Upgrade", municipality: "Mequon", county: "Ozaukee", state: "WI", signalScore: 62, status: "active", projectType: "wtp_upgrade", budgetLow: 3593993, budgetHigh: 6511394 },
  { title: "Watertown Cybersecurity Compliance Upgrade", municipality: "Watertown", county: "Jefferson", state: "WI", signalScore: 62, status: "active", projectType: "cyber_security", budgetLow: 558971, budgetHigh: 1499543 },
  { title: "Waukesha WWTP Upgrade", municipality: "Waukesha", county: "Waukesha", state: "WI", signalScore: 62, status: "active", projectType: "wwtp_upgrade", budgetLow: 5050127, budgetHigh: 41906371 },
  { title: "Greenfield Cybersecurity Compliance Upgrade", municipality: "Greenfield", county: "Milwaukee", state: "WI", signalScore: 61, status: "active", projectType: "cyber_security", budgetLow: 366225, budgetHigh: 1222784 },
  { title: "Brookfield Biosolids Handling Improvements", municipality: "Brookfield", county: "Waukesha", state: "WI", signalScore: 61, status: "active", projectType: "biosolids", budgetLow: 1656537, budgetHigh: 9539218 },
  { title: "Sun Prairie Cybersecurity Compliance Upgrade", municipality: "Sun Prairie", county: "Dane", state: "WI", signalScore: 61, status: "active", projectType: "cyber_security", budgetLow: 343153, budgetHigh: 874156 },
  { title: "Janesville Water Main Replacement", municipality: "Janesville", county: "Rock", state: "WI", signalScore: 60, status: "active", projectType: "water_main", budgetLow: 1085261, budgetHigh: 3025806 },
  { title: "Brookfield WWTP Upgrade", municipality: "Brookfield", county: "Waukesha", state: "WI", signalScore: 60, status: "active", projectType: "wwtp_upgrade", budgetLow: 5716755, budgetHigh: 17557147 },
  { title: "Manitowoc Lift Station Improvements", municipality: "Manitowoc", county: "Manitowoc", state: "WI", signalScore: 59, status: "active", projectType: "lift_station", budgetLow: 1072153, budgetHigh: 3418688 },
  { title: "Sheboygan Well Facility Upgrade", municipality: "Sheboygan", county: "Sheboygan", state: "WI", signalScore: 57, status: "active", projectType: "well_facility", budgetLow: 2176549, budgetHigh: 5932683 },
  { title: "Menasha WWTP Upgrade", municipality: "Menasha", county: "Winnebago", state: "WI", signalScore: 56, status: "active", projectType: "wwtp_upgrade", budgetLow: 5511900, budgetHigh: 11018674 },
  { title: "Milwaukee Collection System Rehabilitation", municipality: "Milwaukee", county: "Milwaukee", state: "WI", signalScore: 56, status: "active", projectType: "collection_system", budgetLow: 2219303, budgetHigh: 2901068 },
  { title: "Mequon WWTP Upgrade", municipality: "Mequon", county: "Ozaukee", state: "WI", signalScore: 56, status: "active", projectType: "wwtp_upgrade", budgetLow: 5989915, budgetHigh: 43186549 },
  { title: "De Pere Water Main Replacement", municipality: "De Pere", county: "Brown", state: "WI", signalScore: 54, status: "active", projectType: "water_main", budgetLow: 1487033, budgetHigh: 5401716 },
  { title: "Appleton Water Treatment Plant Upgrade", municipality: "Appleton", county: "Outagamie", state: "WI", signalScore: 54, status: "active", projectType: "wtp_upgrade", budgetLow: 3712621, budgetHigh: 29440797 },
  { title: "La Crosse Water Main Replacement", municipality: "La Crosse", county: "La Crosse", state: "WI", signalScore: 54, status: "active", projectType: "water_main", budgetLow: 1424607, budgetHigh: 6093681 },
  { title: "Milwaukee Lift Station Improvements", municipality: "Milwaukee", county: "Milwaukee", state: "WI", signalScore: 53, status: "active", projectType: "lift_station", budgetLow: 998468, budgetHigh: 2273840 },
  { title: "Menasha Well Facility Upgrade", municipality: "Menasha", county: "Winnebago", state: "WI", signalScore: 52, status: "active", projectType: "well_facility", budgetLow: 2511180, budgetHigh: 6408968 },
  { title: "Madison SCADA System Upgrade", municipality: "Madison", county: "Dane", state: "WI", signalScore: 52, status: "active", projectType: "scada", budgetLow: 1422782, budgetHigh: 2926426 },
  { title: "Fond du Lac Cybersecurity Compliance Upgrade", municipality: "Fond du Lac", county: "Fond du Lac", state: "WI", signalScore: 51, status: "active", projectType: "cyber_security", budgetLow: 962786, budgetHigh: 1709870 },
  { title: "De Pere Cybersecurity Compliance Upgrade", municipality: "De Pere", county: "Brown", state: "WI", signalScore: 51, status: "active", projectType: "cyber_security", budgetLow: 594739, budgetHigh: 1411401 },
  { title: "Janesville SCADA System Upgrade", municipality: "Janesville", county: "Rock", state: "WI", signalScore: 50, status: "active", projectType: "scada", budgetLow: 844126, budgetHigh: 1375633 },
  { title: "Marshfield Water Storage Tank", municipality: "Marshfield", county: "Wood", state: "WI", signalScore: 50, status: "active", projectType: "storage_tank", budgetLow: 1246116, budgetHigh: 7805197 },
  { title: "Racine Well Facility Upgrade", municipality: "Racine", county: "Racine", state: "WI", signalScore: 49, status: "active", projectType: "well_facility", budgetLow: 2556749, budgetHigh: 5467089 },
  { title: "Brookfield Biosolids Handling Improvements", municipality: "Brookfield", county: "Waukesha", state: "WI", signalScore: 47, status: "active", projectType: "biosolids", budgetLow: 1942463, budgetHigh: 12654526 },
  { title: "Wausau WWTP Upgrade", municipality: "Wausau", county: "Marathon", state: "WI", signalScore: 47, status: "active", projectType: "wwtp_upgrade", budgetLow: 5539323, budgetHigh: 23780697 },
  { title: "Appleton Well Facility Upgrade", municipality: "Appleton", county: "Outagamie", state: "WI", signalScore: 47, status: "active", projectType: "well_facility", budgetLow: 2664256, budgetHigh: 9063786 },
  { title: "BARNEVELD WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BARNEVELD", county: "IOWA", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BARRON CAMERON WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BARRON", county: "BARRON", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BAY CITY VILLAGE - Treatment Improvements", municipality: "BAY CITY", county: "PIERCE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BEAR CREEK WASTEWATER TREAMENT - Treatment Improvements", municipality: "BEAR CREEK", county: "OUTAGAMIE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BELGIUM WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BELGIUM", county: "OZAUKEE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BELL SANITARY DISTRICT 1 - Treatment Improvements", municipality: "CORNUCOPIA", county: "BAYFIELD", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BELLEVILLE WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BELLEVILLE", county: "DANE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BELMONT WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BELMONT", county: "LAFAYETTE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BELOIT TOWN WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "Beloit", county: "Rock", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BELOIT WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "Beloit", county: "Rock", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BENTON WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BENTON", county: "LAFAYETTE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BERLIN CITY WWTF - Treatment Improvements", municipality: "BERLIN", county: "GREEN LAKE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BIRNAMWOOD WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BIRNAMWOOD", county: "SHAWANO", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BLACK CREEK WASTEWATER TREATME - Treatment Improvements", municipality: "BLACK CREEK", county: "OUTAGAMIE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BAILEYS HARBOR WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BAILEYS HARBOR", county: "DOOR", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BLANCHARDVILLE WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BLANCHARDVILLE", county: "LAFAYETTE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BLENKER SHERRY SANITARY DISTRICT WWTF - Treatment Improvements", municipality: "SHERRY", county: "WOOD", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BLOOMER WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BLOOMER", county: "CHIPPEWA", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BLOOMFIELD VILLAGE - Treatment Improvements", municipality: "BLOOMFIELD, TOWN OF", county: "WALWORTH", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BLOOMINGTON WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "BLOOMINGTON", county: "GRANT", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BAGLEY WASTEWATER TREATMENT FA - Treatment Improvements", municipality: "GURNEY", county: "IRON", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BAD RIVER UTILITIES - BIRCH HILL STABILIZATION LAGOON - Treatment Improvements", municipality: "ODANAH", county: "ASHLAND", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BAD RIVER BAND - DIAPERVILLE - Treatment Improvements", municipality: "ODANAH", county: "ASHLAND", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "BAD RIVER  WWWTP - Treatment Improvements", municipality: "ODANAH", county: "ASHLAND", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "AVOCA WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "AVOCA", county: "IOWA", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "AURORA SANITARY DISTRICT # 1 - Treatment Improvements", municipality: "FLORENCE", county: "FLORENCE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "AUGUSTA WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "AUGUSTA", county: "EAU CLAIRE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "AUBURNDALE WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "AUBURNDALE", county: "WOOD", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "ATHENS WASTEWATER TREATMENT FA - Treatment Improvements", municipality: "ATHENS", county: "MARATHON", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "ASHLAND SEWAGE UTILITY - Treatment Improvements", municipality: "ASHLAND", county: "ASHLAND", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "ASHIPPUN SANITARY DISTRICT WWTF - Treatment Improvements", municipality: "ASHIPPUN", county: "DODGE", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
  { title: "ARPIN WASTEWATER TREATMENT FACILITY - Treatment Improvements", municipality: "WOOD COUNTY", county: "WOOD", state: "WI", signalScore: 46, status: "active", projectType: "wwtp_upgrade", budgetLow: 500000, budgetHigh: 5000000 },
]
